### ISSUE TITLE
페이지 구조 설계

### ISSUE THREAD

**Issue by bbanderson** [DDD-6/hermes-web#8]
# 페이지 구조 설계
와이어프레임을 보면서 페이지 인터랙션에 관한 이슈를 정리합니다.

## Goals
- 페이지 별 파일을 pages에 정리하고, mocking data를 추가합니다.

* * *

### 페이지 경로
임의로 지은 path입니다. 협의 후 확정하면 될 것 같습니다.
|경로|기능|
|------|---|
|/|랜딩페이지|
|/join|회원가입|
|/welcome|최초 로그인 시 개인 스페이스 생성|
|/spaces|스페이스 대시보드|
|/spaces/:postId|글 상세페이지|
|/spaces/:postId/new|글 생성페이지|
|/spaces/:postId/edit|에디팅 페이지|
|/push|알림리스트|
|/notice|공지사항|
|/account|계정관리|
- [ ] ❗ 스페이스 내의 각 이어지는 글마다 url을 다르게 만들어서 저장? Vs 스페이스까지만 url 설계?

### 페이지 구조
```
.
├── context
│   └── AuthContext.tsx
└── pages
    ├── _app.tsx
    ├── _document.tsx
    ├── index.tsx
    ├── join.tsx
    ├── welcome.tsx
    ├── push.tsx
    ├── notice.tsx
    ├── account.tsx
    └── spaces
        ├── index.tsx
        └── [postId]
            ├── index.tsx
            ├── new.tsx
            └── edit.tsx
```

#### contextAPI

```tsx
// context/AuthContext.tsx

import { createContext, useContext, ReactNode, useState } from 'react';

type authContextType = {
  user: boolean;
  login: () => void;
  logout: () => void;
};

const authContextDefaultValues: authContextType = {
  user: false,
  login: () => undefined,
  logout: () => undefined,
};

const AuthContext = createContext<authContextType>(authContextDefaultValues);

export function useAuth() {
  return useContext(AuthContext);
}

type Props = {
  children: ReactNode;
};

export function AuthProvider({ children }: Props) {
  console.log('AuthProvider');
  const [user, setUser] = useState<boolean>(false);

  const login = () => {
    console.log('로그인');
    setUser(true);
  };

  const logout = () => {
    console.log('로그아웃');
    setUser(false);
  };

  const value = {
    user,
    login,
    logout,
  };

  return (
    <>
      <AuthContext.Provider value={value}>{children}</AuthContext.Provider>
    </>
  );
}
```

```tsx
// pages/_app.tsx
import type { AppProps } from 'next/app';
import { AuthProvider, useAuth } from '@hermes/app/contexts/AuthContext';
import Head from 'next/head';

import { GlobalStyle } from '@hermes/design-system';

function MyApp({ Component, pageProps }: AppProps) {
  const { user, login, logout } = useAuth();
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>HERMES</title>
      </Head>
      <GlobalStyle />
      <AuthProvider>
        <div>
          {/* 아래 버튼들이 GNB에 있다고 가정 */}
          {user ? '로그인 상태입니다.' : '로그아웃 상태입니다.'}
          {!user ? (
            <button type="button" onClick={login}>
              로그인
            </button>
          ) : (
            <button type="button" onClick={logout}>
              로그아웃
            </button>
          )}
        </div>
        <Component {...pageProps} />
      </AuthProvider>
    </>
  );
}
export default MyApp;

```

####  랜딩페이지`/`
- contextAPI로 인증 상태 조회
  - Pass : `/spaces`로 리다이렉트
  - Fail : 랜딩페이지 렌더링
    - 로그인 시도
      - Pass(이미 회원인 경우)
        - 최초 로그인 판단
          - Pass : `/welcome`으로 리다이렉트
          - Fail(이미 토큰이 있는 경우) : `/spaces`로 리다이렉트
      - Fail(비회원인경우) : `/join`으로 리다이렉트
        - [ ] ❗ 비회원임을 알리는 모달과 함께 `/join`으로 유도하는 것 추가하면 어떨까요?
#### 회원가입 페이지`/join`
- contextAPI로 인증 상태 조회
  - Pass : `/spaces`로 리다이렉트
  - Fail : 회원가입 페이지 렌더링
    - 소셜 로그인 진행
      - Pass : `/welcome`으로 push
      - Fail : 에러 메시지 출력
#### 최초 로그인 시 개인 스페이스 생성 페이지`/welcome`
- contextAPI로 인증 상태 조회
  - Pass : `/spaces`로 리다이렉트
    - [ ] ❗️회원 DB 조회 후, 닉네임 및 최초 개인 스페이스를 생성하지 않고 이탈했었는지 파악
  - Fail : `/welcome` 렌더링
    - 닉네임 설정 진행
      - Pass : 최초 스페이스 생성 컴포넌트 렌더링
        -  [ ] ❗️이모지 관련 패키지 선택 필요
        - Pass : `/spaces`로 push
        - Fail : 에러 메시지 출력
      - Fail : 에러 메시지 출력
#### 스페이스 대시보드 페이지`/spaces`
- contextAPI로 인증 상태 조회
  - Pass : `/spaces` 렌더링
  - Fail : `/`로 리다이렉트

```tsx
// spaces

import { useAuth } from 'contexts/AuthContext';
import { NextPage } from 'next';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

const Spaces: NextPage = () => {
  const { user } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (!user) {
      router.replace('/');
    }
  }, [router, user]);

  return (
    <>
      <div>스페이스 대시보드</div>
    </>
  );
};

export default Spaces;
```
```tsx
// spaces/:postId

import { NextPage } from 'next';
import { useRouter } from 'next/router';

const Post: NextPage = () => {
  const { query } = useRouter();
  return <div>글 {query.postId}</div>;
};

export default Post;
```
